#!/bin/bash

PROG=scc
TST_DIR=examples
RES_DIR=results
LOG_DIR=logs

TESTS="fib array hello malloc params sum" 

# Compile a fresh copy of the SCC executable
make clean
make

# Run SCC, and store output in the appropriate folders
./$PROG < $TST_DIR/fib.c > $RES_DIR/fib.res 2>$LOG_DIR/fib.log

# Compare SCC results to correct answer
diff $RES_DIR/fib.res $TST_DIR/fib.out
