enum{
	ERROR=256, DONE, ID, NUM, STRING, AUTO, BREAK, CASE, CHAR, CONST, CONTINUE, DEFAULT, DO, DOUBLE, ELSE, ENUM, EXTERN, FLOAT, FOR, FOR, GOTO, IF, INT, LONG, REGISTER, RETURN, SHORT, SIGNED, SIZEOF, STATIC, STRUCT, SWITCH, TYPEDEF, UNION, UNSIGNED, VOID, VOLATILE, WHILE, OR, AND, EQUAL, NOTEQUAL, GREATERTHANOREQUAL, LESSTHANOREQUAL, INCREMENT
};
