#!/bin/bash

GREEN=$(tput setaf 2)
RED=$(tput setaf 1)
NORMAL=$(tput sgr0)

PROG=scc
TST_DIR=examples
OUT_DIR=outs
ERR_DIR=errors

# Example files for phase3
TESTS="array global local putchar towers"  

# Compile a fresh copy of the SCC executable ('clear' for aesthetic preference)
clear
make clean
make

if [ $? -ne 0 ]; then
	echo "${RED} Error Compiling During Compilation ${NORMAL}"
	exit 1 
fi

for itest in $TESTS; do
	#print test result banner
	printf "${RED} ******** ${itest} output ******** ${NORMAL}\n"

	# Run SCC, and store output in the appropriate folders
	./$PROG < $TST_DIR/${itest}.c > $OUT_DIR/${itest}.s 2>$ERR_DIR/${itest}.err
	cat $OUT_DIR/${itest}.s
	
	#print foot banner
	printf "\n\n"
done
