#!/bin/bash

PROG=scc
TST_DIR=examples
OUT_DIR=results
ERR_DIR=logs

TESTS="fib array hello malloc params sum" 

# Compile a fresh copy of the SCC executable
clear
make clean
make

for itest in $TESTS; do
	# Run SCC, and store output in the appropriate folders
	./$PROG < $TST_DIR/${itest}.c > $RES_DIR/${itest}.res 2>$ERR_DIR/${itest}.err

	#print test-specific banner
	printf "******** ${itest} results (result < | > correct) ********\n"
	
	# Compare SCC results to correct answer
	diff $RES_DIR/${itest}.res $TST_DIR/${itest}.out
	
	#print foot banner
	printf "******** end ${itest} results ********\n"
done
