#!/bin/bash

PHASE1_DIR=$PWD
TEST_CASE_DIR="test_cases/"
RESULT_DIR="results/"
ANSWER_DIR="answers/"

SOURCE="scc.cpp"
NAME="scc"


# COMPILE PROGRAM
g++ $SOURCE -o $NAME

if [ "$?" == "0" ]
	then
		echo "[INFO] Compilation successful."
	else
		echo "[ERROR] Problem compiling C++ code."
		exit 1
fi


# RUN PROGRAM, STORE RESULTS
./$NAME < test_cases/operators.txt > results/op_test_res.out

if [ "$?" == "0" ]
	then
		echo "[INFO] Program exited without errrors."
	else
		echo "[ERROR] Program exited with errors."
		exit 2
fi

# COMPARE EXPERIMENTAL RESULTS WITH THEORETICAL RESULTS
DIFF=$(diff results/op_test_res.out answers/operators_correct.out)

if [ "$?" != "0" ]
        then
                echo "[ERROR] Problem comparing outputs."
                exit 3
fi

if [ "$DIFF" != "" ]
	then
		echo "[RESULT] Failure. Operator-test results differ."
	else
		echo "[RESULT] Success. Operator-test results match."
fi

exit 0

=======
# Set Up
TEST_NAME=$(basename $1 .txt)

TEST_DIR="test_cases"
ANSW_DIR="answers"
RESU_DIR="results"

if [ ! -d $RESU_DIR ]
  then
    mkdir $RESU_DIR
    echo "[INFO] Created directory for storing scc results."
fi

# Compile
g++ scc.cpp -o scc

if [ "$?" != "0" ]
  then
    echo "[ERROR] Problem compiling program."
    exit 1
  else
    echo "[INFO] Compilation successful."
fi

# Run
./scc < "$TEST_NAME.txt" > "results/$TEST_NAME.res.out"

if [ "$?" != "0" ]
  then
    echo "[ERROR] Problem running program."
    exit 2
  else
    echo "[INFO] Execution successful."
fi

# Compare
DIFF=$(diff results/$TEST_NAME.res.out answers/$TEST_NAME.cor.out)

#if [ "$?" != "0" ]
#  then
#    echo "[ERROR] Problem comparing results."
#    exit 2
#  else
#    echo "[INFO] Comparison successful."
#fi

if [ "$DIFF" == "" ]
  then
    echo "[SUCCESS] Program ouput matches expected output."
  else
    echo "[FAILURE] Program output differs from expected output."
fi

exit 0
