#!/bin/bash

# COMPILE PROGRAM
g++ scc.cpp -o scc

if [ "$?" == "0" ]
	then
		echo "[INFO] Compilation successful."
	else
		echo "[ERROR] Problem compiling C++ code."
		exit 1
fi


# RUN PROGRAM, STORE RESULTS
./scc < test_cases/numbers.txt > results/nu_test_res.out

if [ "$?" == "0" ]
	then
		echo "[INFO] Program exited without errrors."
	else
		echo "[ERROR] Program exited with errors."
		exit 2
fi

# COMPARE EXPERIMENTAL RESULTS WITH THEORETICAL RESULTS
DIFF=$(diff results/nu_test_res.out answers/numbers_correct.out)
if [ "$DIFF" != "" ]
	then
		echo "[RESULT] Failure. Number-test results differ."
	else
		echo "[RESULT] Success. Number-test results match."
fi

exit 0

